### DISCUSSION TITLE
Generation Failed Cuda: Error no karnel image

### DISCUSSION THREAD

**Discussion by vokurta** [PurpleDoubleD/locally-uncensored#37] [General]
i got this error when im trying to generate the image / video

Generation failed: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. (CLIPTextEncode)
<img width="1829" height="959" alt="image" src="https://github.com/user-attachments/assets/659fe5b0-44ef-419c-8dec-2065e81c2ba3" />

Im using Rtx 6000 blakcwell

**Comment by PurpleDoubleD** [comment]
v2.4.4 is out and should fix this on your rtx 6000 blackwell.

the comfyui install step now probes `nvidia-smi --query-gpu=compute_cap` and routes pytorch wheels off the result. sm 8.x and 9.x get the cu121 wheels (existing default), sm 12.0+ get cu128 instead. so blackwell should get a kernel image instead of crashing at `cliptextencode`.

grab v2.4.4 fresh and rerun the comfyui install step. if you still hit no kernel image is available tell me what `nvidia-smi --query-gpu=compute_cap --format=csv,noheader,nounits` prints on your box and ill take another look

**Comment by PurpleDoubleD** [comment]
hey @vokurta, quick check-in. v2.4.4 shipped the blackwell cu128 wheel routing fix on 2026-05-11, and v2.4.5 went out today with unrelated fixes (also auto-updates). on your rtx 6000 blackwell, after auto-update:

1. re-run the comfyui install step (settings > comfyui > reinstall, or trigger a fresh install if you can spare the disk space)
2. the new install should auto-detect SM >= 12.0 via `nvidia-smi --query-gpu=compute_cap` and pull `https://download.pytorch.org/whl/cu128` wheels instead of cu121
3. generate any image to confirm cliptextencode doesnt blow up with the kernel error

if you dont want to nuke your existing install, you can also just `cd <comfyui>/python_embeded/ && Scripts/pip.exe install --force-reinstall torch torchvision --index-url https://download.pytorch.org/whl/cu128` from a terminal, same end-state.

would love a thumbs-up or thumbs-down on whether the kernel error is gone.

— david
